services:
  api:
    build: .
    container_name: kairos_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:7-alpine
    container_name: kairos_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # --- NEW, CRITICAL SERVICE ---
  worker:
    build: .
    container_name: kairos_worker
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    # This command starts the Celery worker.
    command: celery -A app.core.celery_app.celery_app worker --loglevel=info

volumes:
  redis_data: