"""Add source_upload_id to learned_patterns

Revision ID: 641a06b67201
Revises: 812652f96f99
Create Date: 2025-08-11 14:01:03.384761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '641a06b67201'
down_revision: Union[str, Sequence[str], None] = '812652f96f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learned_patterns', sa.Column('source_upload_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_learned_patterns_source_upload_id'), 'learned_patterns', ['source_upload_id'], unique=False)
    op.create_index(op.f('ix_learned_patterns_status'), 'learned_patterns', ['status'], unique=False)
    op.create_foreign_key(None, 'learned_patterns', 'historical_uploads', ['source_upload_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'learned_patterns', type_='foreignkey')
    op.drop_index(op.f('ix_learned_patterns_status'), table_name='learned_patterns')
    op.drop_index(op.f('ix_learned_patterns_source_upload_id'), table_name='learned_patterns')
    op.drop_column('learned_patterns', 'source_upload_id')
    # ### end Alembic commands ###
