"""Add trigger_threshold to learned_patterns

Revision ID: 71b3a59ec25d
Revises: 641a06b67201
Create Date: 2025-08-12 12:01:06.818509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b3a59ec25d'
down_revision: Union[str, Sequence[str], None] = '641a06b67201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learned_patterns', sa.Column('trigger_threshold', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learned_patterns', 'trigger_threshold')
    # ### end Alembic commands ###
