"""Add interaction_id_split to historical_uploads

Revision ID: 812652f96f99
Revises: 33bc43452d5c
Create Date: 2025-08-11 13:38:55.755762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '812652f96f99'
down_revision: Union[str, Sequence[str], None] = '33bc43452d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - CORRECTED ###
    
    # This is the only command that should be in this function.
    op.add_column('historical_uploads', sa.Column('interaction_id_split', sa.JSON(), nullable=True))
    
    # REMOVED: op.create_index(...) - This index already exists.

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - CORRECTED ###
    
    # REMOVED: op.drop_index(...) - This index should remain for the status column.

    # This is the only command that should be in this function.
    op.drop_column('historical_uploads', 'interaction_id_split')

    # ### end Alembic commands ###