"""Add strategy_embedding and threshold to learned_patterns

Revision ID: e7afec2fc3a3
Revises: 71b3a59ec25d
Create Date: 2025-08-12 12:36:40.596744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'e7afec2fc3a3'
down_revision: Union[str, Sequence[str], None] = '71b3a59ec25d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Now that we've imported Vector, this line will work correctly.
    op.add_column('learned_patterns', sa.Column('strategy_embedding', Vector(dim=1536), nullable=True))
    op.add_column('learned_patterns', sa.Column('strategy_threshold', sa.Float(), nullable=True))
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learned_patterns', 'strategy_threshold')
    op.drop_column('learned_patterns', 'strategy_embedding')
    # ### end Alembic commands ###
